/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Employeeproject;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author vishn
 */
public class SearchEmpForm extends javax.swing.JInternalFrame {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    Statement st=null;

    /**
     * Creates new form SearchEmpForm
     */
    public SearchEmpForm() {
        initComponents();
        bind1();//distinct empcode to show
        bind2();//shows distinct departname only shown in combobox
    }
    private void bind1(){//empcode put all value in combobox get from database:
       try{
           String q="select empcode from empdetails";
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
           pst=con.prepareStatement(q);
           rs=pst.executeQuery();
           while(rs.next()){
               empcode.addItem(rs.getString("empcode"));
           }
       }
       catch(SQLException e){
           
           JOptionPane.showMessageDialog(null, e);
       }
   } 
       private void bind2(){//empcode put all value in combobox get from database:
       try{
           String q="select distinct(departname) from empdetails";
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
           pst=con.prepareStatement(q);
           rs=pst.executeQuery();
           while(rs.next()){
               deptname.addItem(rs.getString("departname"));
           }
       }
       catch(SQLException e){
           
           JOptionPane.showMessageDialog(null, e);
       }
   } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        empcode = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        landline = new javax.swing.JTextField();
        deptname = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        empsearch = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(995, 600));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("M/S.DUMMY PVT. LTD.");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("View Employee Record Form");

        jLabel4.setText("Enter Emp Code:-");

        empcode.setEnabled(false);
        empcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empcodeActionPerformed(evt);
            }
        });

        jButton3.setText("Search Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter First Name:-");

        jLabel6.setText("Enter Last Name:-");

        jLabel7.setText("Enter Mobile:-");

        jLabel8.setText("Enter Landline:-");

        jLabel9.setText("Enter DeptName:-");

        firstname.setEnabled(false);

        lastname.setEnabled(false);
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });

        mobile.setEnabled(false);
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });

        landline.setEnabled(false);

        deptname.setEnabled(false);
        deptname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptnameActionPerformed(evt);
            }
        });

        jLabel10.setText("Select Search Option:-");

        empsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select from below", "Empcode", "Firstname", "Lastname", "Mobileno", "Landline", "Deptname" }));
        empsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empsearchActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(empsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jButton3)))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(empcode, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(firstname))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(landline))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 589, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deptname, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(empsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(landline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(deptname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empcodeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_empcodeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            switch (empsearch.getSelectedIndex()) {
                case 1 -> {
                    String e=empcode.getSelectedItem().toString();
                    String q;
                    q = "select * from empdetails where empcode='"+e+"'";
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                    pst=con.prepareStatement(q);
                    rs=pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
                case 2 ->                     {
                        String f=firstname.getText();
                        String s;
                        s = "select * from empdetails where firstname like '"+f+"%'";
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                        pst=con.prepareStatement(s);
                        rs=pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                case 3 ->                     {
                        String l;
                        l = lastname.getText();
                        String s="select * from empdetails where lastname like'"+l+"%'";
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                        pst=con.prepareStatement(s);
                        rs=pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                case 4 ->                     {
                        String m;
                        m = mobile.getText();
                        String s="select * from empdetails where mobile like'"+m+"%'";
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                        pst=con.prepareStatement(s);
                        rs=pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                case 5 ->                     {
                        String l;
                        l = landline.getText();
                        String s="select * from empdetails where landline like'"+l+"%'";
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                        pst=con.prepareStatement(s);
                        rs=pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                case 6 ->                     {
                        String d;
                        d = deptname.getSelectedItem().toString();
                        String s="select * from empdetails where departname ='"+d+"'";
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                        pst=con.prepareStatement(s);
                        rs=pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                default -> {
                }
            }
        }
        catch(SQLException e){

            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        empsearch.setSelectedIndex(0);
        DefaultTableModel dm=(DefaultTableModel)jTable1.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void deptnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptnameActionPerformed

    private void empsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empsearchActionPerformed
        // TODO add your handling code here:
        switch (empsearch.getSelectedIndex()) {
            
            case 1 -> {
                empcode.setSelectedIndex(0);
                deptname.setSelectedIndex(0);
                firstname.setText(" ");
                lastname.setText(" ");
                mobile.setText(" ");
                landline.setText(" ");
                empcode.setEnabled(true);
                firstname.setEnabled(false);
                lastname.setEnabled(false);
                mobile.setEnabled(false);
                landline.setEnabled(false);
                deptname.setEnabled(false);
            }
            case 2 -> {
                empcode.setSelectedIndex(0);
                deptname.setSelectedIndex(0);
                firstname.setText(" ");
                lastname.setText(" ");
                mobile.setText(" ");
                landline.setText(" ");
                firstname.setEnabled(true);
                empcode.setEnabled(false);
                lastname.setEnabled(false);
                mobile.setEnabled(false);
                landline.setEnabled(false);
                deptname.setEnabled(false);
            }
            case 3 -> {
                empcode.setSelectedIndex(0);
                deptname.setSelectedIndex(0);
               firstname.setText(" ");
                lastname.setText(" ");
                mobile.setText(" ");
                landline.setText(" ");
                firstname.setEnabled(false);
                empcode.setEnabled(false);
                lastname.setEnabled(true);
                mobile.setEnabled(false);
                landline.setEnabled(false);
                deptname.setEnabled(false);
            }
            case 4 -> {
                empcode.setSelectedIndex(0);
                deptname.setSelectedIndex(0);
                firstname.setText(" ");
                lastname.setText(" ");
                mobile.setText(" ");
                landline.setText(" ");
                firstname.setEnabled(false);
                empcode.setEnabled(false);
                lastname.setEnabled(false);
                mobile.setEnabled(true);
                landline.setEnabled(false);
                deptname.setEnabled(false);
            }
            case 5 -> {
                empcode.setSelectedIndex(0);
                deptname.setSelectedIndex(0);
                firstname.setText(" ");
                lastname.setText(" ");
                mobile.setText(" ");
                landline.setText(" ");
                landline.setEnabled(true);
                empcode.setEnabled(false);
                lastname.setEnabled(false);
                mobile.setEnabled(false);
                firstname.setEnabled(false);
                deptname.setEnabled(false);
            }
            case 6 -> {
                empcode.setSelectedIndex(0);
                deptname.setSelectedIndex(0);
                firstname.setText(" ");
                lastname.setText(" ");
                mobile.setText(" ");
                landline.setText(" ");
                firstname.setEnabled(false);
                empcode.setEnabled(false);
                lastname.setEnabled(false);
                mobile.setEnabled(false);
                landline.setEnabled(false);
                deptname.setEnabled(true);
            }
            default -> {
                //JOptionPane.showMessageDialog(null,"Please Select Proper Index");
                empcode.setSelectedIndex(0);
                deptname.setSelectedIndex(0);
                firstname.setText(" ");
                lastname.setText(" ");
                mobile.setText(" ");
                landline.setText(" ");
                empcode.setEnabled(false);
                firstname.setEnabled(false);
                lastname.setEnabled(false);
                mobile.setEnabled(false);
                landline.setEnabled(false);
                deptname.setEnabled(false);
            }
        }
    
           
        
        
    }//GEN-LAST:event_empsearchActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> deptname;
    private javax.swing.JComboBox<String> empcode;
    private javax.swing.JComboBox<String> empsearch;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField landline;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField mobile;
    // End of variables declaration//GEN-END:variables
}
