/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Employeeproject;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author vishn
 */
public class Viewsalaryform extends javax.swing.JInternalFrame {
Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    Statement st=null;
    /**
     * Creates new form Viewsalaryform
     */
    public Viewsalaryform() {
        initComponents();
        bind();
    }
    public void bind(){
        try{
           String q="select empcode from saldetails";
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
           pst=con.prepareStatement(q);
           rs=pst.executeQuery();
           while(rs.next()){
               empcode.addItem(rs.getString("empcode"));
           }
       }
       catch(SQLException e){
           
           JOptionPane.showMessageDialog(null, e);
       }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        empsearch = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        empcode = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        salfrom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        salto = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("M/S.DUMMY PVT. LTD.");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("View Employee Salary Form");

        jLabel10.setText("Select Search Option:-");

        empsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select from Below", "empcode", "firstname", "lastname", "salary", "Range of salary" }));
        empsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empsearchActionPerformed(evt);
            }
        });

        jButton1.setText("Search Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Enter Emp Code:-");

        empcode.setEnabled(false);
        empcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empcodeActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter First Name:-");

        jLabel6.setText("Enter Last Name:-");

        jLabel7.setText("Enter Salary:-");

        salary.setEnabled(false);

        jLabel8.setText("Enter salary range from:-");

        salfrom.setEnabled(false);
        salfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salfromActionPerformed(evt);
            }
        });

        jLabel9.setText("Enter salary range to:-");

        salto.setEnabled(false);
        salto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saltoActionPerformed(evt);
            }
        });

        firstname.setText(" ");
        firstname.setEnabled(false);

        lastname.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(445, 445, 445))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(111, 111, 111)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(154, 154, 154)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(55, 55, 55)
                                    .addComponent(empsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(salary)
                                .addComponent(empcode, 0, 162, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(firstname)
                                .addComponent(salfrom))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(salto, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(lastname))
                            .addGap(67, 67, 67)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButton1)
                .addGap(367, 367, 367)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(empsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(salfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(salto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empsearchActionPerformed
        // TODO add your handling code here:
        if(empsearch.getSelectedIndex()==0){
             empcode.setSelectedIndex(0);
                salary.setText(" ");
                firstname.setText(" ");
                lastname.setText(" ");
                salfrom.setText(" ");
                salto.setText(" ");
                empcode.setEnabled(false);
                firstname.setEnabled(false);
                lastname.setEnabled(false);
                salary.setEnabled(false);
                salfrom.setEnabled(false);
                salto.setEnabled(false);
                
        }

        else if(empsearch.getSelectedIndex()==1){
                empcode.setSelectedIndex(0);
                salary.setText(" ");
                firstname.setText(" ");
                lastname.setText(" ");
                salfrom.setText(" ");
                salto.setText(" ");
                empcode.setEnabled(true);
                firstname.setEnabled(false);
                lastname.setEnabled(false);
                salary.setEnabled(false);
                salfrom.setEnabled(false);
                salto.setEnabled(false);
            }
        else  if(empsearch.getSelectedIndex()==2) {
                empcode.setSelectedIndex(0);
                firstname.setText(" ");
                lastname.setText(" ");
                salary.setText(" ");
                salfrom.setText(" ");
                salto.setText(" ");
                firstname.setEnabled(true);
                empcode.setEnabled(false);
                lastname.setEnabled(false);
                salary.setEnabled(false);
                salfrom.setEnabled(false);
                salto.setEnabled(false);
            }
            else if(empsearch.getSelectedIndex()==3){
                empcode.setSelectedIndex(0);
                firstname.setText(" ");
                lastname.setText(" ");
                salary.setText(" ");
                salfrom.setText(" ");
                salto.setText(" ");
                firstname.setEnabled(false);
                empcode.setEnabled(false);
                lastname.setEnabled(true);
                salary.setEnabled(false);
                salfrom.setEnabled(false);
                salto.setEnabled(false);
            }
            else if(empsearch.getSelectedIndex()==4) {
                empcode.setSelectedIndex(0);
                firstname.setText(" ");
                lastname.setText(" ");
                salary.setText(" ");
                salfrom.setText(" ");
                salto.setText(" ");
                firstname.setEnabled(false);
                empcode.setEnabled(false);
                lastname.setEnabled(false);
                salary.setEnabled(true);
                salfrom.setEnabled(false);
                salto.setEnabled(false);
            }
            else if(empsearch.getSelectedIndex()==5){
                empcode.setSelectedIndex(0);
                firstname.setText(" ");
                lastname.setText(" ");
                salary.setText(" ");
                salfrom.setText(" ");
                salto.setText(" ");
                empcode.setEnabled(false);
                lastname.setEnabled(false);
                firstname.setEnabled(false);
                salary.setEnabled(false);
                salfrom.setEnabled(true);
                salto.setEnabled(true);
            }
           
           else{
               JOptionPane.showMessageDialog(null, "Select Valid Index");
               empcode.setSelectedIndex(0);
                firstname.setText(" ");
                lastname.setText(" ");
                salary.setText(" ");
                salfrom.setText(" ");
                salto.setText(" ");
                firstname.setEnabled(false);
                empcode.setEnabled(false);
                lastname.setEnabled(false);
                salary.setEnabled(false);
                salfrom.setEnabled(false);
                salto.setEnabled(false);
            }
        

    }//GEN-LAST:event_empsearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            if(empsearch.getSelectedIndex()==1) 
               {
                    String empcode=this.empcode.getSelectedItem().toString();
                    String q="select * from saldetails where empcode='"+empcode+"'";
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                    pst=con.prepareStatement(q);
                    rs=pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
               else if(empsearch.getSelectedIndex()==2){
                    String firstname=this.firstname.getText();
                    //JOptionPane.showMessageDialog(null, firstname);
                    String s="select * from saldetails where firstname like '%"+firstname+"%'";
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                    pst=con.prepareStatement(s);
                    rs=pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
                else if(empsearch.getSelectedIndex()==3){
                    String lastname=this.lastname.getText();
                    String s="select * from saldetails where lastname like'%"+lastname+"%'";
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                    pst=con.prepareStatement(s);
                    rs=pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
               else if(empsearch.getSelectedIndex()==4){
                    Double sal=Double.parseDouble(salary.getText());
                    String s="select * from saldetails where netsalary = "+sal+"";
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                    pst=con.prepareStatement(s);
                    rs=pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
                else if(empsearch.getSelectedIndex()==5){
                    Double salfrom=Double.parseDouble(this.salfrom.getText());
                    Double salto=Double.parseDouble(this.salto.getText());
                    String s="select * from saldetails where netsalary BETWEEN "+salfrom+" AND "+salto+"";
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                    pst=con.prepareStatement(s);
                    rs=pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
              }
        catch(SQLException e){

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        empsearch.setSelectedIndex(0);
        DefaultTableModel dm=(DefaultTableModel)jTable1.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void empcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empcodeActionPerformed

    private void saltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saltoActionPerformed

    private void salfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salfromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salfromActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> empcode;
    private javax.swing.JComboBox<String> empsearch;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField salary;
    private javax.swing.JTextField salfrom;
    private javax.swing.JTextField salto;
    // End of variables declaration//GEN-END:variables
}
