/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Employeeproject;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author vishn
 */
public class ViewSalarygenerate extends javax.swing.JInternalFrame {
Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    Statement st=null;
    /**
     * Creates new form ViewSalarygenerate
     */
    public ViewSalarygenerate() {
        initComponents();
         bind();
        bind1();
    }
    private void bind(){
     try{
           String q="select empcode from monthsal";
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
           pst=con.prepareStatement(q);
           rs=pst.executeQuery();
           while(rs.next()){
               empcode.addItem(rs.getString("empcode"));
           }
       }
       catch(SQLException e){
           
           JOptionPane.showMessageDialog(null, e);
       }
        
    }
private void bind1(){
     try{
           String q="select distinct(salarymonth) from monthsal";
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
           pst=con.prepareStatement(q);
           rs=pst.executeQuery();
           while(rs.next()){
               attmonth.addItem(rs.getString("salarymonth"));
           }
       }
       catch(SQLException e){
           
           JOptionPane.showMessageDialog(null, e);
       }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        empsearch1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        empcode = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        attmonth = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dayspresent = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        sal = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("M/S.DUMMY PVT. LTD.");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("View Salary Generate Form");

        jLabel10.setText("Select Search Option:-");

        empsearch1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select from Below", "empcode", "firstname", "lastname", "Attendancemonth", "dayspresent", "Monthly Salary" }));
        empsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empsearch1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter Emp Code:-");

        empcode.setEnabled(false);
        empcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empcodeActionPerformed(evt);
            }
        });

        jLabel9.setText("AttendanceMonth:-");

        attmonth.setEnabled(false);
        attmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attmonthActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter First Name:-");

        firstname.setEnabled(false);

        jLabel6.setText("Enter last Name:-");

        lastname.setEnabled(false);
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });

        jLabel8.setText("No of Days Present:-");

        dayspresent.setEnabled(false);

        jButton1.setText("Search Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Monthly Salary:-");

        sal.setEnabled(false);
        sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jButton1)
                                .addGap(367, 367, 367)
                                .addComponent(jButton2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(attmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(empcode, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(empsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(dayspresent, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(empsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(empcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayspresent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(attmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empsearch1ActionPerformed
        // TODO add your handling code here:
        if(empsearch1.getSelectedIndex()==0){
            empcode.setSelectedIndex(0);
            dayspresent.setText(" ");
            firstname.setText(" ");
            lastname.setText(" ");
            attmonth.setSelectedIndex(0);
            sal.setText(" ");
            sal.setEnabled(false);
            attmonth.setEnabled(false);
            firstname.setEnabled(false);
            lastname.setEnabled(false);
            empcode.setEnabled(false);
            dayspresent.setEnabled(false);

        }

        else if(empsearch1.getSelectedIndex()==1){
            attmonth.setSelectedIndex(0);
            empcode.setSelectedIndex(0);
            dayspresent.setText(" ");
            firstname.setText(" ");
            lastname.setText(" ");
            sal.setText(" ");
            sal.setEnabled(false);
            dayspresent.setEnabled(false);
            empcode.setEnabled(true);
            attmonth.setEnabled(false);
            firstname.setEnabled(false);
            lastname.setEnabled(false);

        }
        else  if(empsearch1.getSelectedIndex()==2) {
            attmonth.setSelectedIndex(0);
            empcode.setSelectedIndex(0);
            firstname.setText(" ");
            lastname.setText(" ");
            dayspresent.setText(" ");
            sal.setText(" ");
            sal.setEnabled(false);
            firstname.setEnabled(true);
            attmonth.setEnabled(false);
            empcode.setEnabled(false);
            lastname.setEnabled(false);
            dayspresent.setEnabled(false);

        }
        else if(empsearch1.getSelectedIndex()==3){
            attmonth.setSelectedIndex(0);
            empcode.setSelectedIndex(0);
            firstname.setText(" ");
            lastname.setText(" ");
            dayspresent.setText(" ");
            sal.setText(" ");
            sal.setEnabled(false);
            dayspresent.setEnabled(false);
            firstname.setEnabled(false);
            attmonth.setEnabled(false);
            lastname.setEnabled(true);
            empcode.setEnabled(false);
        }
        else if(empsearch1.getSelectedIndex()==4) {
            attmonth.setSelectedIndex(0);
            empcode.setSelectedIndex(0);
            firstname.setText(" ");
            lastname.setText(" ");
            dayspresent.setText(" ");
            sal.setText(" ");
            sal.setEnabled(false);
            dayspresent.setEnabled(false);
            firstname.setEnabled(false);
            attmonth.setEnabled(true);
            lastname.setEnabled(false);
            empcode.setEnabled(false);
        }
        else if(empsearch1.getSelectedIndex()==5){
            attmonth.setSelectedIndex(0);
            empcode.setSelectedIndex(0);
            firstname.setText(" ");
            lastname.setText(" ");
            dayspresent.setText(" ");
            sal.setText(" ");
            sal.setEnabled(false);
            empcode.setEnabled(false);
            attmonth.setEnabled(false);
            lastname.setEnabled(false);
            firstname.setEnabled(false);
            dayspresent.setEnabled(true);
        }
        else if(empsearch1.getSelectedIndex()==6){
            attmonth.setSelectedIndex(0);
            empcode.setSelectedIndex(0);
            firstname.setText(" ");
            lastname.setText(" ");
            dayspresent.setText(" ");
            sal.setText(" ");
            sal.setEnabled(true);
            empcode.setEnabled(false);
            attmonth.setEnabled(false);
            lastname.setEnabled(false);
            firstname.setEnabled(false);
            dayspresent.setEnabled(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Select Valid Index");
            empcode.setSelectedIndex(0);
            dayspresent.setText(" ");
            firstname.setText(" ");
            lastname.setText(" ");
            sal.setText(" ");
            sal.setEnabled(false);
            attmonth.setSelectedIndex(0);
            attmonth.setEnabled(false);
            firstname.setEnabled(false);
            lastname.setEnabled(false);
            empcode.setEnabled(false);
            dayspresent.setEnabled(false);

        }

    }//GEN-LAST:event_empsearch1ActionPerformed

    private void empcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empcodeActionPerformed

    private void attmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attmonthActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            if(empsearch1.getSelectedIndex()==1)
            {
                String empcode=this.empcode.getSelectedItem().toString();
                String q="select * from monthsal where empcode='"+empcode+"'";
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else if(empsearch1.getSelectedIndex()==2){
                String firstname=this.firstname.getText();
                //JOptionPane.showMessageDialog(null, firstname);
                String s1="select * from monthsal where firstname like '"+firstname+"%'";
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                pst=con.prepareStatement(s1);
                rs=pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else if(empsearch1.getSelectedIndex()==3){
                String lastname=this.lastname.getText();
                String s2="select * from monthsal where lastname like'"+lastname+"%'";
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                pst=con.prepareStatement(s2);
                rs=pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }else if(empsearch1.getSelectedIndex()==4){
                String attmonth=this.attmonth.getSelectedItem().toString();
                String s3="select * from monthsal where salarymonth='"+attmonth+"'";
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                pst=con.prepareStatement(s3);
                rs=pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));

            }
            else if(empsearch1.getSelectedIndex()==5){
                String d=dayspresent.getText();
                String s3="select * from monthsal where noofdayspresent="+d+"";
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                pst=con.prepareStatement(s3);
                rs=pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));

            }
             else if(empsearch1.getSelectedIndex()==6){
                String s=sal.getText();
                String s3="select * from monthsal where salary="+s+"";
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","root");
                pst=con.prepareStatement(s3);
                rs=pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));

            }

        }
        catch(SQLException e){

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        empsearch1.setSelectedIndex(0);
        DefaultTableModel dm=(DefaultTableModel)jTable1.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> attmonth;
    private javax.swing.JTextField dayspresent;
    private javax.swing.JComboBox<String> empcode;
    private javax.swing.JComboBox<String> empsearch1;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField sal;
    // End of variables declaration//GEN-END:variables
}
